# GitHub Actions workflow
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions

name: CI

on:
  pull_request:
    branches:
      # - development
      - master
  push:
    branches:
      # - development
      - master
    tags-ignore:
      - '*'
jobs:
  test:
    name: Lint & Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-20.04
        node:
          - 16.14.x

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Test the code
        run: npm run test:ci

      - name: Lint the code
        run: npm run lint -- --max-warnings 0

      - name: Check types
        run: npm run typescript:server

      - name: Build the code
        run: npm run build
